//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipProdu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipProdu()
        {
            this.Produses = new HashSet<Produse>();
        }
    
        public int IDTipProdus { get; set; }
        public string Nume { get; set; }
        public string UnitateMasura { get; set; }
        public int PretKg { get; set; }
        public int Cantitate { get; set; }
        public int TermenGarantie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produse> Produses { get; set; }
    }
}
