//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vanzari
    {
        public int IDVanzari { get; set; }
        public Nullable<int> IDProdus { get; set; }
        public Nullable<System.DateTime> DataVanzare { get; set; }
    
        public virtual Produse Produse { get; set; }
    }
}
